name: "Build Substitutes"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - pkgs/**
      - .github/workflows/build-substitutes.yml
jobs:
  strongswan-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#strongswan-unstable
  nixverse:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#nixverse
  emacs-unstable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#emacs-unstable
  tailscale-utils-unstable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#tailscale-utils-unstable
  p0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#p0 &>/dev/null
  p1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#p1 &>/dev/null
  p2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: hgl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link .#p2 &>/dev/null
